// Credentials for Nessa App project: Ordem Github Account
export const supabaseUrl = "https://sbxyggqdcpugvegizety.supabase.co";
export const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNieHlnZ3FkY3B1Z3ZlZ2l6ZXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjg5NDg1ODksImV4cCI6MjA0NDUyNDU4OX0.dp-R_L6EH3bqKcLkiqslpKop9dnqzNEFCbJomVeKzHU";